window.LAB_META = {
  "generatedAt": "2026-10-03",
  "labCount": 61,
  "contactCount": 15,
  "sortRule": "score DESC → citations DESC → 原序",
  "note": "具身LAB排名 · 高校实验室数据，来源：全球TOP100具身智能团队深度调研.xlsx（2026-10-03 版）；发表情况悬停于「论文得分」列查看"
};

window.LAB_RANKING = [
  {
    "id": 1,
    "university": "斯坦福大学",
    "lab": "Stanford Vision and Learning Lab",
    "person": "李飞飞",
    "citations": 227434,
    "person_intro": "斯坦福计算机科学系首任红杉教授、以人为本AI研究院（HAI）联合创始主任，曾任谷歌云AI/ML首席科学家，现为空间智能公司 World Labs 联合创始人兼CEO。",
    "publications": "CVPR 90 篇、NeurIPS 35 篇、ICRA 12 篇、IROS 6 篇、CoRL 4 篇、RSS 2 篇，3 分档论文累计 149 篇，其余 ICML、ICLR、顶刊等共 251 篇",
    "team_size": "100-500",
    "lab_intro": "聚焦视觉驱动的具身智能、物理常识推理与家庭服务机器人。",
    "website": "https://ai.stanford.edu/",
    "score": 798,
    "contact": true,
    "contact_note": "使用AgibotWorld数据集",
    "rank": 1
  },
  {
    "id": 2,
    "university": "麻省理工学院",
    "lab": "LIS 实验室",
    "person": "Leslie Pack Kaelbling",
    "citations": 21287,
    "person_intro": "MIT 松下计算机科学与工程教授，以将部分可观测马尔可夫决策过程（POMDP）应用于机器人与强化学习而知名。",
    "publications": "RSS 7 篇、ICRA 28 篇、IROS 12 篇、CoRL 4 篇、NeurIPS 15 篇、CVPR 1 篇",
    "team_size": "",
    "lab_intro": "融合运动与任务规划、机器学习、强化学习与计算机视觉，构建能在广泛问题域中智能行动的机器人系统。",
    "website": "https://lis.csail.mit.edu/people/",
    "score": 494,
    "contact": "",
    "contact_note": "",
    "rank": 2
  },
  {
    "id": 3,
    "university": "美国纽约大学",
    "lab": "CILVR",
    "person": "Sam Bowman\nJoan Bruna等",
    "citations": 57690,
    "person_intro": "纽约大学数据科学与计算机科学副教授，CILVR 与 ML² 小组成员，2022–24 年领导对齐研究小组，2016 年获博士学位。",
    "publications": "CVPR 22 篇、NeurIPS 18 篇、ICRA 25 篇、IROS 12 篇、CoRL 9 篇、RSS 4 篇，3 分档论文累计 90 篇，其余 ICLR、ICML 218 篇",
    "team_size": "50-100",
    "lab_intro": "研究 3D 轨迹空间世界建模与跨具身视频学习。",
    "website": "https://wp.nyu.edu/cilvr/",
    "score": 488,
    "contact": true,
    "contact_note": "Shusheng Yang（博士生）\nEllis Brown（博士生）\nShengbang Tong（名单里标注为 Shengbang ”Peter” Tong，同一人）\nRob Fergus（实验室联合主任）\nYann LeCun（实验室主任）\nSaining Xie（教职老师）等作者来自该实验室，Cambrian‑S 提出空间超感知新范式，将视频理解分为语义感知、流事件认知、隐式 3D 空间认知作为无标注真实视频数据源，AGIBOT WORLD作为无标注真实视频数据源，纳入 VSI‑590K 空间指令微调数据集\n提供4,844 条机器人视频，用于提升模型空间感知与物体计数能力",
    "rank": 3
  },
  {
    "id": 4,
    "university": "麻省理工学院",
    "lab": "MIT Robot Locomotion Group",
    "person": "Russ Tedrake",
    "citations": 20882,
    "person_intro": "MIT 教授，获 2024 年 MIT 工程学院杰出教育者奖、NSF CAREER 奖与 DARPA 数学青年学者奖等多项荣誉。",
    "publications": "RSS 18 篇、ICRA 42 篇、IROS 15 篇、CoRL 12 篇、NeurIPS 9 篇、CVPR 3 篇",
    "team_size": "",
    "lab_intro": "研究人形机器人动力学与控制、崎岖地形动态行走、无人机激进机动与软体机器人反馈控制，隶属 Robotics @ MIT 与 CSAIL。",
    "website": "https://locomotion.csail.mit.edu/index.html",
    "score": 483,
    "contact": "",
    "contact_note": "",
    "rank": 4
  },
  {
    "id": 5,
    "university": "华盛顿大学",
    "lab": "Personal Robotics Lab",
    "person": "Siddhartha Srinivasa",
    "citations": 21846,
    "person_intro": "华盛顿大学教授，2006 年创立个人机器人实验室，致力于让机器人在杂乱与不确定环境中与人协作完成操作任务，主导构建 HERB、ADA、CHIMP 等端到端系统。",
    "publications": "CVPR 2 篇、NeurIPS 2 篇、ICRA 65 篇、IROS 33 篇、CoRL 8 篇、RSS 16 篇，论文累计 126 篇，其余期刊等 101 篇",
    "team_size": "10-50",
    "lab_intro": "发展感知、操作、学习与人机交互的基础模块，使机器人能在杂乱和不确定环境下执行复杂物理操作，受英特尔与 NSF 资助。",
    "website": "https://personalrobotics.cs.washington.edu/",
    "score": 479,
    "contact": "",
    "contact_note": "",
    "rank": 5
  },
  {
    "id": 6,
    "university": "斯坦福大学",
    "lab": "ILIAD",
    "person": "Dorsa Sadigh",
    "citations": 34941,
    "person_intro": "斯坦福计算机科学副教授，研究机器人学与机器学习交叉，专注从人类反馈中学习并适应人类影响的机器人学习算法。",
    "publications": "RSS 24 篇、ICRA 28 篇、IROS 8 篇、CoRL 33 篇、NeurIPS 11 篇、CVPR 1 篇，合计 105 篇、累计 315 分，其余成果 98 篇",
    "team_size": "10-50",
    "lab_intro": "为交互式机器人学习开发理论与算法，融合机器学习、控制论与认知科学，构建能与人无缝协调、协作或竞争的机器人策略。",
    "website": "https://iliad.stanford.edu/people/",
    "score": 413,
    "contact": "",
    "contact_note": "",
    "rank": 6
  },
  {
    "id": 7,
    "university": "加州大学伯克利",
    "lab": "BAIR Lab",
    "person": "Pieter Abbeel",
    "citations": 202781,
    "person_intro": "伯克利 Jim Gray 工程讲席教授、BAIR 实验室主任，研究强化学习与机器人学习。",
    "publications": "NeurIPS 29 篇、CVPR 3 篇、ICRA 14 篇、IROS 10 篇、CoRL 13 篇、RSS 7 篇，3 分档论文累计 76 篇，其余成果 64 篇",
    "team_size": "",
    "lab_intro": "研究强化学习、模仿学习、机器人基础模型与低成本机器人平台（DexArm、LoCoBot）。",
    "website": "https://bair.berkeley.edu/people/faculty",
    "score": 392,
    "contact": true,
    "contact_note": "使用AgibotWorld数据集",
    "rank": 7
  },
  {
    "id": 8,
    "university": "斯坦福大学",
    "lab": "IPRL 实验室",
    "person": "Jeannette Bohg",
    "citations": 22413,
    "person_intro": "斯坦福计算机科学助理教授、交互感知与机器人学习实验室主任，专注机器人抓握与操作中的感觉运动协调。",
    "publications": "RSS 6 篇、ICRA 41 篇、IROS 21 篇、CoRL 22 篇、NeurIPS 1 篇、CVPR 3 篇，3 分档论文合计 94 篇、累计 282 分，其余成果 88 篇",
    "team_size": "",
    "lab_intro": "在机器人学、机器学习与计算机视觉的交叉处，探索人类强健感觉运动协调的基础原理并应用于自主机器人操控。",
    "website": "https://web.stanford.edu/~bohg/",
    "score": 370,
    "contact": "",
    "contact_note": "",
    "rank": 8
  },
  {
    "id": 9,
    "university": "卡耐基梅隆大学",
    "lab": "AIRLAB",
    "person": "Sebastian Scherer",
    "citations": 14931,
    "person_intro": "卡内基梅隆大学机器人研究所副研究教授。",
    "publications": "CVPR 6 篇、NeurIPS 4 篇、ICRA 28 篇、IROS 28 篇、CoRL 4 篇、RSS 6 篇，3 分档论文累计 76 篇，其余成果 118 篇",
    "team_size": "50-100",
    "lab_intro": "研究自主系统在复杂环境中的感知、规划与导航，涵盖空中与地面机器人。",
    "website": "https://theairlab.org/publications/",
    "score": 346,
    "contact": "",
    "contact_note": "",
    "rank": 9
  },
  {
    "id": 10,
    "university": "ETH（苏黎世联邦理工学院）",
    "lab": "Autonomous Systems Lab",
    "person": "Roland Siegwart",
    "citations": 50611,
    "person_intro": "苏黎世联邦理工学院机械工程正教授，国际移动机器人领域权威学者。",
    "publications": "IROS 2025、RSS 42 篇，其余 212 篇",
    "team_size": "",
    "lab_intro": "研究自主机器人、SLAM、环境感知与运动控制，是国际移动机器人顶尖团队。",
    "website": "https://asl.ethz.ch/the-lab/people/person-detail.siegwart.html",
    "score": 338,
    "contact": "",
    "contact_note": "",
    "rank": 10
  },
  {
    "id": 11,
    "university": "复旦大学",
    "lab": "视觉与学习实验室",
    "person": "姜育刚",
    "citations": 29530,
    "person_intro": "复旦大学教授、智能机器人与先进制造创新学院院长，研究多模态AI与具身智能，国家自然科学基金创新群体带头人。",
    "publications": "NeurIPS 25 篇、CVPR 32 篇，其余 ICCV、ECCV、ICLR、AAAI、TPAMI 等共 157 篇",
    "team_size": "10-50",
    "lab_intro": "从事计算机视觉与机器学习理论与应用研究，目标是研发准确、快速、可扩展且值得信赖的 AI 算法。",
    "website": "https://fvl.fudan.edu.cn/",
    "score": 328,
    "contact": "",
    "contact_note": "",
    "rank": 11
  },
  {
    "id": 12,
    "university": "德克萨斯大学",
    "lab": "UT Austin Robot Perception and Learning Lab",
    "person": "Yuke Zhu",
    "citations": 33792,
    "person_intro": "德克萨斯大学奥斯汀分校副教授、RPL 实验室主任，兼任 NVIDIA 杰出研究科学家，共同领导通用具身智能团队（GEAR）。",
    "publications": "CVPR 16 篇、ICRA 32 篇、CoRL 22 篇、RSS 15 篇、NeurIPS 10 篇、ICLR 11 篇等，其余成果 33 篇",
    "team_size": "50-100",
    "lab_intro": "研究机器人学与具身AI中感知与行为的协同关系，构建支撑通用机器人自主性的算法与系统。",
    "website": "https://rpl.cs.utexas.edu/",
    "score": 309,
    "contact": "",
    "contact_note": "",
    "rank": 12
  },
  {
    "id": 13,
    "university": "斯坦福大学",
    "lab": "REAL 实验室",
    "person": "Shuran Song（宋舒兰）",
    "citations": 41699,
    "person_intro": "斯坦福大学助理教授、REAL 实验室负责人，开发让智能系统从与物理世界的互动中自主学习感知与操作技能的算法。",
    "publications": "RSS 11 篇、ICRA 22 篇、IROS 8 篇、CoRL 17 篇、NeurIPS 4 篇、CVPR 12 篇，3 分档论文合计 74 篇、累计 222 分，其余成果 56 篇",
    "team_size": "10-50",
    "lab_intro": "研究全身灵巧操作、视觉-语言-动作融合、3D 场景理解与具身 Transformer 模型。",
    "website": "https://real.stanford.edu/",
    "score": 278,
    "contact": "",
    "contact_note": "",
    "rank": 13
  },
  {
    "id": 14,
    "university": "上海交通大学",
    "lab": "Machine Vision and Intelligence Group",
    "person": "卢策吾",
    "citations": 27192,
    "person_intro": "上海交通大学教授、长江学者特聘教授，获科学探索奖，入选 MIT TR35 中国区榜单，2022 年获教育部青年科学奖。",
    "publications": "CVPR 43 篇、ICRA 9 篇、RSS 3 篇、IROS 4 篇、CoRL 2 篇、NeurIPS 2 篇，3 分档论文合计 63 篇、累计 189 分，其余成果 82 篇",
    "team_size": "10-50",
    "lab_intro": "研究方向为通用机器人（具身智能），强调智能体主动与物理环境交互，而非被动接收信息。",
    "website": "https://www.mvig.org/index.html",
    "score": 271,
    "contact": "",
    "contact_note": "",
    "rank": 14
  },
  {
    "id": 15,
    "university": "加州理工学院",
    "lab": "Autonomous Systems and Robotics Lab",
    "person": "Soon-Jo Chung",
    "citations": 7530,
    "person_intro": "加州理工学院控制与动力系统 Bren 教授，获 AIAA 制导导航与控制最佳论文奖、IEEE RA-L 最佳论文荣誉提名。",
    "publications": "ICRA 15 篇、IROS 16 篇、NeurIPS 3 篇、RSS 2 篇，其余期刊与顶会 159 篇",
    "team_size": "",
    "lab_intro": "专注动态行走、安全控制与人形机器人（AMBER 系列），强调形式化验证与学习结合。",
    "website": "https://aerospacerobotics.caltech.edu/prof-soonjo-chung",
    "score": 267,
    "contact": "",
    "contact_note": "",
    "rank": 15
  },
  {
    "id": 16,
    "university": "北京航空航天大学",
    "lab": "Colab 实验室",
    "person": "思柳\n任广辉\n林江黄",
    "citations": 15333,
    "person_intro": "北航教授，研究具身智能与多模态内容理解，CCF-A 类论文众多（含 IEEE T-PAMI 17 篇），获 ACM MM 最佳论文奖等多项奖项。",
    "publications": "CVPR 40 篇、NeurIPS 7 篇、ICRA 2 篇、IROS 2 篇，3 分档论文合计 51 篇，其余 ICLR、AAAI、ICCV",
    "team_size": "10-50",
    "lab_intro": "专注将 AI 技术与无人机、具身智能体和卫星遥感等前沿平台结合。",
    "website": "http://www.colalab.net/",
    "score": 264,
    "contact": true,
    "contact_note": "联合提出 ACoT-VLA1. 联合提出 ACoT-VLA（Action Chain-of-Thought）架构，入选 CVPR 2026\n2. 首次提出在 \"动作空间\" 进行推理的思维链范式\n3. ACoT-VLA 已作为 AGIBOT WORLD CHALLENGE 官方基线模型正式开源",
    "rank": 16
  },
  {
    "id": 17,
    "university": "北京大学",
    "lab": "北大 - 智元机器人联合实验室",
    "person": "董豪",
    "citations": 10746,
    "person_intro": "北京大学长聘副教授，研究具身智能与机器人学习，顶会/期刊论文 90 余篇、引用超万次，获 CEAI 杰出青年研究者论文奖提名。",
    "publications": "ICRA 18 篇、CVPR 18 篇、NeurIPS 12 篇、IROS 10 篇、RSS 4 篇、CoRL 7 篇，3 分档论文合计 69 篇、累计 207 分，其余 ICLR、ICML、AAAI 等",
    "team_size": "10-50",
    "lab_intro": "北大与智元机器人共建实验室，代表成果包括 CrayonRobo（CVPR 2025）、ET-SEED（ICLR 2025）、GarmentPile++ 与 NavSpace（ICRA 2026）等机器人操作与导航工作。",
    "website": "https://zsdonghao.github.io/",
    "score": 247,
    "contact": true,
    "contact_note": "AT-VLA 自适应触觉视觉语言动作模型，依托 AgiBot World 预训练的 GO-1 作为骨干",
    "rank": 17
  },
  {
    "id": 18,
    "university": "清华大学",
    "lab": "MARS 多模态学习实验室",
    "person": "赵行",
    "citations": 33613,
    "person_intro": "清华大学交叉信息院助理教授、MARS 实验室负责人，曾任 Waymo 研究科学家，2019 年获 MIT 博士学位。",
    "publications": "ICRA 14 篇、CoRL 13 篇、CVPR 19 篇、IROS 10 篇、NeurIPS 5 篇、RSS 1 篇，3 分档论文合计 62 篇，其余 ICCV、ICLR、ICML、ECCV 30 篇",
    "team_size": "50-100",
    "lab_intro": "清华交叉信息院交叉学科 AI 实验室，研究多模态学习基础问题及其在自动驾驶、机器人与多传感器融合上的应用。",
    "website": "https://group.iiis.tsinghua.edu.cn/~marslab/#/",
    "score": 246,
    "contact": "",
    "contact_note": "",
    "rank": 18
  },
  {
    "id": 19,
    "university": "牛津大学",
    "lab": "Dynamic Robot Systems Group",
    "person": "Maurice Fallon",
    "citations": 5575,
    "person_intro": "牛津大学机器人学教授，曾任 MIT 团队在 DARPA 机器人挑战赛中的感知负责人，2017 年获皇家学会大学研究员职位。",
    "publications": "ICRA 24 篇、IROS 15 篇、CoRL 4 篇、RSS 4 篇、NeurIPS 2 篇，3 分档论文累计 49 篇、合计 147 分，其余 IEEE 汇刊等 86 篇",
    "team_size": "",
    "lab_intro": "隶属牛津工程科学系，研究腿式机器人、自动驾驶、空中机器人与手持测绘系统的状态估计与感知。",
    "website": "https://dynamic.robots.ox.ac.uk/",
    "score": 231,
    "contact": "",
    "contact_note": "",
    "rank": 19
  },
  {
    "id": 20,
    "university": "麻省理工学院",
    "lab": "Improbable AI 实验室",
    "person": "Pulkit Agrawal",
    "citations": 14200,
    "person_intro": "MIT EECS 副教授，实验室隶属 CSAIL，伯克利博士，曾共同创办 SafelyYou 公司。",
    "publications": "ICRA 16 篇、NeurIPS 13 篇、CoRL 11 篇、RSS 4 篇、IROS 4 篇、CVPR 2 篇，3 分档论文合计 50 篇、累计 150 分，其余 72 篇",
    "team_size": "",
    "lab_intro": "提出「物理常识」学习框架，开发能解决复杂物理交互问题的机器人智能体，在 CoRL、Nature 等发表多篇里程碑论文。",
    "website": "https://improbable-ai.mit.edu/",
    "score": 222,
    "contact": "",
    "contact_note": "",
    "rank": 20
  },
  {
    "id": 21,
    "university": "复旦大学",
    "lab": "EDLAB",
    "person": "陈涛",
    "citations": 6749,
    "person_intro": "复旦大学教授，曾任职新加坡智能机器人实验室、新加坡信息通信研究院与华为新加坡研究中心，2019 年加入复旦。",
    "publications": "CVPR 19 篇、NeurIPS 12 篇、ICRA 1 篇，其余成果 108 篇",
    "team_size": "10-50",
    "lab_intro": "研究具身 AI 模型压缩、高效推理与边缘部署。",
    "website": "https://eetchen.github.io/publications/",
    "score": 214,
    "contact": "",
    "contact_note": "",
    "rank": 21
  },
  {
    "id": 22,
    "university": "ETH（苏黎世联邦理工学院）",
    "lab": "Robotic Systems Lab (RSL)",
    "person": "Marco Hutter",
    "citations": 31332,
    "person_intro": "苏黎世联邦理工学院机械与工艺工程系正教授。",
    "publications": "ICRA 16 篇、IROS 14 篇、CoRL 6 篇、RSS 4 篇、CVPR 1 篇，3 分档论文合计 41 篇、得分 123 分，其余 85 篇",
    "team_size": "",
    "lab_intro": "研究腿式机器人学习与控制、四足机器人（ANYmal 系列）与地形自适应运动，代表成果 ANYmal 是全球最具影响力的腿式平台之一。",
    "website": "https://rsl.ethz.ch/the-lab/people.html",
    "score": 208,
    "contact": "",
    "contact_note": "",
    "rank": 22
  },
  {
    "id": 23,
    "university": "清华大学",
    "lab": "具身智能实验室（TEA Lab）",
    "person": "许华哲",
    "citations": 6519,
    "person_intro": "清华大学助理教授、TEA Lab 创始负责人，曾在斯坦福视觉与学习实验室（SVL）从事博士后研究。",
    "publications": "ICRA 11 篇、NeurIPS 13 篇、CoRL 7 篇、RSS 6 篇、CVPR 4 篇、IROS 3 篇，其余 ICML、ICLR、ECCV 等 62 篇",
    "team_size": "10",
    "lab_intro": "专注具身智能、跨模态感知与机器人自主决策，目标是让机器人真正看懂世界并主动完成复杂多变的任务。",
    "website": "http://hxu.rocks/publication.html",
    "score": 194,
    "contact": "",
    "contact_note": "",
    "rank": 23
  },
  {
    "id": 24,
    "university": "上海交通大学",
    "lab": "IRMV 实验室",
    "person": "王贺升",
    "citations": 8979,
    "person_intro": "上海交通大学唐君远讲席教授，香港中文大学博士，兼任自动化学会混合智能专委会副主任。",
    "publications": "ICRA 19 篇、CVPR 12 篇、IROS 9 篇、NeurIPS 3 篇，3 分档论文合计 43 篇、累计 129 分，其余成果 59 篇",
    "team_size": "",
    "lab_intro": "隶属上海交大自动化与感知学院，研究视觉伺服、自动驾驶、软体/人形/医疗机器人、多智能体控制与强化学习。",
    "website": "https://irmv.sjtu.edu.cn/cn",
    "score": 188,
    "contact": "",
    "contact_note": "",
    "rank": 24
  },
  {
    "id": 25,
    "university": "麻省理工学院",
    "lab": "Phillip Isola's Group",
    "person": "Phillip Isola",
    "citations": 106976,
    "person_intro": "MIT EECS 副教授，研究计算机视觉、机器学习与人工智能，曾任 OpenAI 访问研究科学家、伯克利博士后。",
    "publications": "NeurIPS 18 篇、CVPR 6 篇、CoRL 5 篇、IROS 4 篇、ICRA 3 篇，3 分档论文合计 36 篇、得分 108 分，其余成果 72 篇",
    "team_size": "10-50",
    "lab_intro": "目标是理解智能的基本原理，尤其关注由神经网络构建、具高度适应性与通用性、能从具身互动中涌现的类人智能。",
    "website": "https://web.mit.edu/phillipi/#ResearchGroup",
    "score": 180,
    "contact": "",
    "contact_note": "",
    "rank": 25
  },
  {
    "id": 26,
    "university": "北京大学",
    "lab": "北大-灵初联合实验室",
    "person": "杨耀东\n陈源培",
    "citations": 15117,
    "person_intro": "杨耀东：实验室首席科学家，顶会顶刊论文百余篇，获 ACL'25 最佳论文奖与 CoRL'20 最佳系统论文奖；陈源培：北大 AI 研究院硕士，NeurIPS'22 比赛冠军。",
    "publications": "NeurIPS 32 篇、ICRA 2 篇、CoRL 3 篇、IROS 1 篇、ICCV 1 篇，无 RSS 发表，其余 ICML、ICLR、AAAI 30 篇",
    "team_size": "50-100",
    "lab_intro": "北大与灵初智能共建实验室，深耕通用具身智能、VLA 大模型与灵巧操作，推出端到端强化学习具身模型 Psi R0/R0.5/R1。",
    "website": "",
    "score": 177,
    "contact": true,
    "contact_note": "使用G1机器人",
    "rank": 26
  },
  {
    "id": 27,
    "university": "MIT",
    "lab": "MIT HAN Lab",
    "person": "韩松（Han Song）",
    "citations": 82586,
    "person_intro": "MIT EECS 终身副教授，斯坦福博士，开创「深度压缩」与高效推理引擎，其论文入选 ISCA 五十年史上被引最高的五篇之一。",
    "publications": "CVPR 18 篇、NeurIPS 12 篇，ICLR、ICML、ASPLOS、FPGA 76 分",
    "team_size": "",
    "lab_intro": "研究高效深度学习计算，聚焦模型压缩、高效推理与面向机器人的高效神经网络。",
    "website": "https://hanlab.mit.edu/publications",
    "score": 166,
    "contact": true,
    "contact_note": "使用AGIBOT WORLD数据集",
    "rank": 27
  },
  {
    "id": 28,
    "university": "上海交通大学",
    "lab": "SJTU-ReThinkLab",
    "person": "严俊池",
    "citations": 35653,
    "person_intro": "上海交通大学教授（终身教职），IAPR/IET/AAIA/NAAI Fellow，曾任 IBM 研究院首席研究员与 AWS AI 实验室研究员。",
    "publications": "CVPR 8 篇、NeurIPS 10 篇、ECCV 6 篇、ICCV 1 篇等，3 分档论文累计 27 篇、合计 81 分，其余 78 篇",
    "team_size": "10-50",
    "lab_intro": "研究自动驾驶与机器人的环境感知、决策规划与操作控制，以及图与组合优化的机器学习。",
    "website": "https://thinklab.sjtu.edu.cn/member.html",
    "score": 159,
    "contact": "",
    "contact_note": "",
    "rank": 28
  },
  {
    "id": 29,
    "university": "香港大学",
    "lab": "MMLab",
    "person": "Ping Luo（罗平）",
    "citations": 91449,
    "person_intro": "香港大学计算机科学系副教授、数据科学学院副主任，港中大博士，师从汤晓鸥与王晓刚。",
    "publications": "CVPR 25 篇、NeurIPS 12 篇，3 分档论文合计 37 篇、累计 111 分，其余成果 37 篇",
    "team_size": "10",
    "lab_intro": "研究 3D 具身导航与目标定位（ReGround3D）、4D 场景生成（TC4D）与具身规划评估（EgoPlan-Bench）。",
    "website": "https://mmlab.hk/about-us",
    "score": 148,
    "contact": true,
    "contact_note": "参与agibot world数据集建设",
    "rank": 29
  },
  {
    "id": 30,
    "university": "多伦多大学",
    "lab": "Toronto Intelligent Systems Lab (TISL)",
    "person": "Igor Gilitschenski\nMahsa Golchoubian",
    "citations": 4722,
    "person_intro": "Igor Gilitschenski：多伦多大学助理教授，曾在 MIT CSAIL 从事研究，ETH 博士；Mahsa Golchoubian：多伦多大学博士后，研究安全智能的自主决策，滑铁卢大学博士。",
    "publications": "ICRA 5 篇、NeurIPS 6 篇、CVPR 4 篇、IROS 3 篇、CoRL 3 篇、RSS 1 篇，其余成果 28 篇",
    "team_size": "50-100",
    "lab_intro": "研究受人类学习启发的具身AI与机器人学习，聚焦高效场景表示、仿真环境基础模型与新颖感知方式。",
    "website": "https://tisl.cs.toronto.edu/",
    "score": 122,
    "contact": "",
    "contact_note": "",
    "rank": 30
  },
  {
    "id": 31,
    "university": "帝国理工学院",
    "lab": "多尺度具身智能实验室",
    "person": "张丹丹",
    "citations": 1623,
    "person_intro": "帝国理工学院生物工程系讲师（助理教授）、多尺度具身智能实验室主任，兼 I-X 项目 AI 与机器学习讲师。",
    "publications": "ICRA 14 篇、IROS 10 篇、CVPR 1 篇，IEEE T-RO 等期刊 44 篇",
    "team_size": "10-50",
    "lab_intro": "专注开发跨多个物理尺度的具身智能系统。",
    "website": "https://www.intelligentrobotics-acrossscales.com/",
    "score": 119,
    "contact": "",
    "contact_note": "",
    "rank": 31
  },
  {
    "id": 32,
    "university": "新加坡国立大学",
    "lab": "邵林团队",
    "person": "邵林",
    "citations": 1587,
    "person_intro": "新加坡国立大学计算机学院计算机科学系助理教授。",
    "publications": "ICRA 16 篇、IROS 7 篇、CoRL 5 篇、RSS 3 篇、NeurIPS 2 篇、CVPR 1 篇，3 分档论文合计 34 篇、累计 102 分，其余 17 篇",
    "team_size": "50-100",
    "lab_intro": "构建能在物理世界中执行多样化任务的通用机器人系统，赋予机器人感知与操作能力。",
    "website": "https://linsats.github.io/",
    "score": 119,
    "contact": true,
    "contact_note": "使用AgibotWorld数据集",
    "rank": 32
  },
  {
    "id": 33,
    "university": "西湖大学",
    "lab": "MiLAB",
    "person": "王东临",
    "citations": 4173,
    "person_intro": "西湖大学副教授、国家科技创新 2030 重大项目首席科学家，卡尔加里大学博士，长期在加拿大与美国从事机器人智能研究。",
    "publications": "NeurIPS 32 篇、CoRL 3 篇、ICRA 2 篇、IROS 1 篇，3 分档论文合计 39 篇、累计 117 分",
    "team_size": "10-50",
    "lab_intro": "聚焦机器人学习：强化学习理论、元学习理论与机器人行为智能，目标是让真实机器人更灵活、适应更快、能自主学习。",
    "website": "",
    "score": 117,
    "contact": true,
    "contact_note": "CUBic论文明确列出王东临、丁鹏翔的西湖大学署名；真实实验使用 AgiBot双臂机器人，开展抓取、物体交接、放置等6项任务。",
    "rank": 33
  },
  {
    "id": 34,
    "university": "南加州大学",
    "lab": "南加州大学 RASC",
    "person": "Daniel Seita",
    "citations": 2147,
    "person_intro": "南加州大学计算机科学助理教授，研究机器人对视觉与几何复杂物体的操作。",
    "publications": "ICRA 17 篇、CoRL 7 篇、IROS 4 篇、ICLR 3 篇、CVPR 1 篇、RSS 1 篇，其余 13 篇",
    "team_size": "10-50",
    "lab_intro": "研究机器人对几何与感知困难物体的可靠操作（SLURM 实验室），面向真实而杂乱的环境。",
    "website": "https://slurm-lab-usc.github.io/",
    "score": 112,
    "contact": "",
    "contact_note": "",
    "rank": 34
  },
  {
    "id": 57,
    "university": "香港大学",
    "lab": "机器人系统（MaRS）实验室",
    "person": "张富",
    "citations": 9895,
    "person_intro": "香港大学机械工程系副教授（终身），中科大本科、伯克利博士，研究无人机设计导航控制与激光雷达 SLAM。",
    "publications": "ICRA 8 篇、IROS 9 篇，3 分档论文合计 17 篇、累计 51 分，其余 Science Robotics、T-RO 等 58 篇",
    "team_size": "10-50",
    "lab_intro": "研究软体机器人抓手、微创手术用柔性连续体机器人与仿生机器人。",
    "website": "https://mars.hku.hk/publications.html",
    "score": 108,
    "contact": "",
    "contact_note": "",
    "rank": 35
  },
  {
    "id": 35,
    "university": "南洋理工大学",
    "lab": "PINE Lab",
    "person": "Ziwei Wang",
    "citations": 1858,
    "person_intro": "南洋理工大学 EEE 学院助理教授、感知与具身智能（PINE）实验室主任，曾在 CMU 机器人研究所做博士后，2023 年获清华博士学位。",
    "publications": "CVPR 14 篇、IROS 5 篇、CoRL 4 篇、ICRA 3 篇、NeurIPS 2 篇，其余期刊与会议 24 篇",
    "team_size": "10-50",
    "lab_intro": "目标是打造像人类一样感知并与物理世界互动的具身智能体，协助人们完成日常复杂任务。",
    "website": "https://pine-lab-ntu.github.io/team.html",
    "score": 108,
    "contact": "",
    "contact_note": "",
    "rank": 36
  },
  {
    "id": 36,
    "university": "香港中文大学",
    "lab": "具身智能研究中心（港中大（深圳）数据科学学院）",
    "person": "贺品嘉\n贾奎",
    "citations": 15223,
    "person_intro": "贺品嘉：港中大（深圳）助理教授、国家级青年人才，ICSE/FSE/ICLR 等顶会论文 60 余篇，获 IEEE TCSE Rising Star 奖；贾奎：同院教授，研究三维视觉与具身智能。",
    "publications": "CVPR 11 篇、NeurIPS 3 篇，ICSE、FSE、ICLR、ACL、OSDI 等顶会论文 60 余篇",
    "team_size": "10",
    "lab_intro": "研究多模态感知（视觉、语言、触觉融合）、强化与模仿学习、智能体自主决策与生成式具身智能。",
    "website": "https://sds.cuhk.edu.cn/page/2125",
    "score": 102,
    "contact": "",
    "contact_note": "",
    "rank": 37
  },
  {
    "id": 37,
    "university": "北京大学",
    "lab": "EPIC LAB",
    "person": "王鹤",
    "citations": 7005,
    "person_intro": "北京大学前沿计算研究中心助理教授、博导，EPIC Lab 创始人，兼任北大-银河通用具身智能联合实验室主任与智源研究院具身智能中心主任。",
    "publications": "CVPR 23 篇、ICRA 2 篇、IROS 1 篇、NeurIPS 1 篇，其余 ICLR、AAAI、ECCV、ICCV 6 篇",
    "team_size": "10-50",
    "lab_intro": "专注具身感知与交互、三维视觉，开发高度通用且可扩展的机器人视觉与控制系统。",
    "website": "https://pku-epic.github.io/",
    "score": 97,
    "contact": true,
    "contact_note": "LDA-1B项目使用包含 3276小时AgiBot World数据的EI-30k数据集，并使用AgiBot World留出集评测",
    "rank": 38
  },
  {
    "id": 56,
    "university": "香港中文大学（深圳）数据科学学院",
    "lab": "智能自主系统实验室 LIAS",
    "person": "吴俊峰",
    "citations": null,
    "person_intro": "港中大（深圳）副教授，香港科技大学电子与计算机工程系博士。",
    "publications": "ICRA 6 篇、IROS 1 篇，3 分档论文合计 7 篇、累计 21 分，其余 IEEE 顶刊、Automatica 等 71 篇",
    "team_size": "",
    "lab_intro": "研究自主导航、环境理解与任务规划，为具身智能体提供底层控制与决策能力。",
    "website": "https://lias-cuhksz.github.io/publications/",
    "score": 97,
    "contact": "",
    "contact_note": "",
    "rank": 39
  },
  {
    "id": 38,
    "university": "宾夕法尼亚大学",
    "lab": "智能机器人实验室（JIRL）",
    "person": "Antonio Loquercio",
    "citations": 6365,
    "person_intro": "宾夕法尼亚大学助理教授，苏黎世大学博士（师从 Davide Scaramuzza），曾在伯克利 BAIR 做博士后。",
    "publications": "ICRA 14 篇、CVPR 4 篇、ECCV 2 篇、NeurIPS 1 篇、CoRL 2 篇、RSS 1 篇，其余 8 篇",
    "team_size": "10",
    "lab_intro": "汇聚机器人学、AI、控制论与计算机视觉，构建能在复杂环境中感知、推理与行动的智能机器人。",
    "website": "https://jirl-upenn.github.io/index.html",
    "score": 94,
    "contact": "",
    "contact_note": "",
    "rank": 40
  },
  {
    "id": 39,
    "university": "清华大学",
    "lab": "具身视觉与机器人实验室 EVAR LAB",
    "person": "高阳",
    "citations": 5149,
    "person_intro": "清华大学交叉信息研究院助理教授、上海期智研究院 PI，伯克利博士（师从 Trevor Darrell），提出 EfficientZero、ViLa、CoPa 等通用具身算法框架。",
    "publications": "CoRL 8 篇、NeurIPS 6 篇、IROS 4 篇、ICRA 3 篇、RSS 1 篇，其余 ICCV、ICML、ICLR 等 10 篇",
    "team_size": "10",
    "lab_intro": "隶属清华交叉信息研究院，专注用 AI 赋能机器人，打造通用的具身智能框架。",
    "website": "https://iiis.tsinghua.edu.cn/kxyj/ktzjs/sjyjqrsys_VAR_.htm",
    "score": 91,
    "contact": "",
    "contact_note": "",
    "rank": 41
  },
  {
    "id": 40,
    "university": "香港大学",
    "lab": "OpenDriveLab",
    "person": "李弘扬",
    "citations": 13734,
    "person_intro": "香港大学助理教授、OpenDriveLab 负责人，领导端到端自动驾驶项目 UniAD，获 CVPR 2023 最佳论文奖。",
    "publications": "CVPR 8 篇、NeurIPS 7 篇、RSS 2 篇、IROS 2 篇、CoRL 1 篇，3 分档论文合计 20 篇、累计 60 分，其余 28 篇",
    "team_size": "10-50",
    "lab_intro": "研究自动驾驶与具身智能，代表工作包括 UniAD、AgiBot World、EgoPlan-Bench 等。",
    "website": "https://opendrivelab.com/team",
    "score": 88,
    "contact": true,
    "contact_note": "使用AgibotWorld数据集",
    "rank": 42
  },
  {
    "id": 42,
    "university": "南京大学",
    "lab": "Reasoning and Learning",
    "person": "高阳",
    "citations": 23798,
    "person_intro": "南京大学教授，研究多智能体系统、强化学习、信念修正与智能系统理论。",
    "publications": "NeurIPS、CVPR 12 篇，其余 ICML、ICLR、ICCV、ECCV、AAAI 51 篇",
    "team_size": "50-100",
    "lab_intro": "隶属南大计算机软件新技术国家重点实验室，研究 AI 理论与方法、通用大模型、具身智能与 AI 智能体、AI for Science 等。",
    "website": "https://cs.nju.edu.cn/gaoyang/",
    "score": 87,
    "contact": "",
    "contact_note": "",
    "rank": 43
  },
  {
    "id": 41,
    "university": "宾夕法尼亚大学",
    "lab": "DAIR Lab",
    "person": "Michael Posa",
    "citations": 2159,
    "person_intro": "宾夕法尼亚大学助理教授、GRASP 实验室 DAIR 组负责人，MIT 博士、斯坦福学士，研究机器人的动态安全交互。",
    "publications": "ICRA 9 篇、RSS 4 篇、CoRL 3 篇、IROS 3 篇，其余 30 篇",
    "team_size": "10-50",
    "lab_intro": "研究机器人与世界交互中的控制、学习、规划与分析，开发计算可行且数据高效的动态安全算法。",
    "website": "https://dair.seas.upenn.edu/",
    "score": 87,
    "contact": "",
    "contact_note": "",
    "rank": 44
  },
  {
    "id": 43,
    "university": "香港科技大学",
    "lab": "HKUST-GZ PEAK 实验室",
    "person": "陈昶昊",
    "citations": 3541,
    "person_intro": "港科大（广州）助理教授、博导，牛津大学计算机科学博士，PEAK Lab 课题组长。",
    "publications": "ICRA 4 篇、CVPR 3 篇、IROS 2 篇、NeurIPS 1 篇，3 分档论文合计 10 篇、累计 30 分，其余 51 篇",
    "team_size": "10",
    "lab_intro": "研究基于视觉语言大模型的人形机器人交互、自主导航讲解机器人，以及家庭服务与工业协助应用。",
    "website": "https://changhao-chen.github.io/people/",
    "score": 81,
    "contact": "",
    "contact_note": "",
    "rank": 45
  },
  {
    "id": 44,
    "university": "卡耐基梅隆大学",
    "lab": "HARP 实验室",
    "person": "Henny Admoni",
    "citations": 3639,
    "person_intro": "卡内基梅隆大学机器人研究所副教授、HARP 实验室负责人，耶鲁博士，研究人机交互、辅助机器人与非语言交流。",
    "publications": "IROS 7 篇、CoRL 4 篇、RSS 2 篇、ICRA 2 篇，ICLR/HRI/AAMAS 等 33 篇",
    "team_size": "10-50",
    "lab_intro": "开发辅助与协作机器人及人工智能，以改善人们的生活。",
    "website": "https://harplab.github.io/harplab.deploy/",
    "score": 78,
    "contact": "",
    "contact_note": "",
    "rank": 46
  },
  {
    "id": 45,
    "university": "同济大学",
    "lab": "同济大学自主智能无人系统科学中心",
    "person": "蒋永康",
    "citations": 419,
    "person_intro": "同济大学电子与信息工程学院助理教授，上海市「晨光学者」，北航博士、洛桑联邦理工访问学者，研究方向为智能机器人。",
    "publications": "ICRA 2024 共 1 篇，ICML、IJCAI、IEEE 顶刊、RA-L 等 54 篇",
    "team_size": "50-100",
    "lab_intro": "专注跨空间、跨任务、跨具身学习，研发无界大模型与机器人世界模型。",
    "website": "https://robot.tongji.edu.cn/kxyj2/fb.htm",
    "score": 57,
    "contact": true,
    "contact_note": "使用AgibotWorld数据集",
    "rank": 47
  },
  {
    "id": 46,
    "university": "南洋理工大学",
    "lab": "MARS Lab",
    "person": "Jianfei Yang",
    "citations": 8693,
    "person_intro": "南洋理工大学助理教授，入选斯坦福全球前 2% 顶尖科学家与《福布斯亚洲》30 Under 30，研究物理AI、多模态大模型与机器人学。",
    "publications": "NeurIPS 5 篇、CVPR 3 篇、ICRA 2 篇、IROS 2 篇，共 12 篇、得分 36 分，其余 ICLR、AAAI、ECCV 20 篇",
    "team_size": "",
    "lab_intro": "通过创新的 AI 算法、数据集与系统推动前沿机器人与人工智能技术。",
    "website": "https://marslab.tech/projects/",
    "score": 56,
    "contact": "",
    "contact_note": "",
    "rank": 48
  },
  {
    "id": 47,
    "university": "麻省理工学院",
    "lab": "CLEAR LAB",
    "person": "Andreea Bobu",
    "citations": 1031,
    "person_intro": "MIT 助理教授，伯克利博士（师从 Anca Dragan）。",
    "publications": "ICRA 4 篇、CoRL 2 篇、IROS 1 篇，其余 ICML、ICLR、HRI 等 25 篇",
    "team_size": "10-50",
    "lab_intro": "研究自动驾驶、机器人操作与 AI 助手等自主智能体和人类之间无缝、符合人类期望的交互。",
    "website": "https://www.mit.edu/~abobu/",
    "score": 46,
    "contact": "",
    "contact_note": "",
    "rank": 49
  },
  {
    "id": 48,
    "university": "清华大学",
    "lab": "智能系统与机器人实验室（ISR Lab）",
    "person": "陈建宇",
    "citations": 4059,
    "person_intro": "清华大学交叉信息研究院助理教授，伯克利博士（2020）、清华学士（2015）。",
    "publications": "IROS 6 篇、NeurIPS 4 篇、ICRA 3 篇、CoRL 1 篇、CVPR 1 篇，3 分档论文合计 15 篇",
    "team_size": "10",
    "lab_intro": "由陈建宇创立，隶属清华 IIIS，目标打造高性能且高智能的先进机器人系统，横跨机器人学、强化学习与大语言模型。",
    "website": "https://group.iiis.tsinghua.edu.cn/~isrlab/",
    "score": 45,
    "contact": true,
    "contact_note": "陈建宇，郭江延都来自（ISRLab）实验室，他们共同发表了论文Ctrl-World：一种用于机器人操作的可控生成世界模型。这篇论文引用Genie Envisioner，Ctrl-World 是在 Genie Envisioner 等视频生成 / 世界模型的研究基础上，针对机器人政策的闭环评估与优化提出的可控多视图生成式世界模型",
    "rank": 50
  },
  {
    "id": 49,
    "university": "ETH（苏黎世联邦理工学院）",
    "lab": "Spatial AI Lab（微软合作）",
    "person": "Stefan Leutenegger",
    "citations": 15360,
    "person_intro": "苏黎世联邦理工学院机械与工艺工程系副教授。",
    "publications": "ICRA 3 篇、CVPR 1 篇、IROS 2 篇、ICCV 1 篇，其余 20 篇",
    "team_size": "",
    "lab_intro": "运用基础模型、大语言模型与模仿/强化学习，开发能扩展到开放环境与多样任务的空间AI移动机器人。",
    "website": "https://mrl.ethz.ch/publications.html",
    "score": 41,
    "contact": "",
    "contact_note": "",
    "rank": 51
  },
  {
    "id": 50,
    "university": "香港科技大学",
    "lab": "Precognition Lab",
    "person": "梁俊卫",
    "citations": 2409,
    "person_intro": "港科大（广州）助理教授，曾任腾讯优图高级研究员，CMU 博士，获百度奖学金与雅虎奖学金。",
    "publications": "CoRL 4 篇、ICRA 2 篇、NeurIPS 2 篇、CVPR 2 篇、IROS 1 篇，3 分档论文合计 11 篇、累计 33 分，其余 7 篇",
    "team_size": "10-50",
    "lab_intro": "致力于构建能有效感知、推理并与现实世界互动的具身智能系统。",
    "website": "https://precognition.team/",
    "score": 40,
    "contact": "",
    "contact_note": "",
    "rank": 52
  },
  {
    "id": 51,
    "university": "上海交通大学",
    "lab": "空间认知与机器人自主智能实验室（ScaleLab）",
    "person": "穆尧\n陈天行",
    "citations": 3542,
    "person_intro": "上海交通大学人工智能研究院长聘教轨助理教授，毕业于清华与港大计算机系，顶会顶刊论文 30 余篇。",
    "publications": "NeurIPS 4 篇、ICLR 5 篇、ICML 4 篇、ICRA 3 篇、CVPR 2 篇等",
    "team_size": "10-50",
    "lab_intro": "隶属上海交大人工智能研究院，由杨小康教授指导建设，主要从事具身智能与机器人领域的前沿学术研究。",
    "website": "https://scalelab-sjtu.github.io/index.html",
    "score": 39,
    "contact": true,
    "contact_note": "参与Agibot-world项目，发布世界最大规模真实机器人数据集",
    "rank": 53
  },
  {
    "id": 52,
    "university": "西湖大学",
    "lab": "自主智能实验室（Autolab）",
    "person": "于开丞",
    "citations": null,
    "person_intro": "西湖大学助理教授、博导，2023 年创立 AutoLab，曾任英特尔实验室与阿里达摩院研究员，EPFL 博士。",
    "publications": "CVPR 3 篇、NeurIPS 1 篇、CoRL 1 篇，其余 ICLR、AAAI、ECCV 等 18 篇",
    "team_size": "",
    "lab_intro": "构建以数据驱动世界模型为核心的下一代自主智能系统，聚焦 AI4Reality（具身智能与自动驾驶数据闭环）与 AI4Virtual（科学智能）两大方向。",
    "website": "https://westlake-autolab.github.io/people.html",
    "score": 33,
    "contact": "",
    "contact_note": "",
    "rank": 54
  },
  {
    "id": 53,
    "university": "复旦大学（替补）",
    "lab": "OpenMOSS 团队",
    "person": "邱锡鹏",
    "citations": null,
    "person_intro": "复旦大学教授、CAAI Fellow，主持开发大语言模型 MOSS 与开源 NLP 工具链，研究方向为大模型与智能体。",
    "publications": "NeurIPS 2 篇、ICLR 1 篇、ACL 1 篇，其他会议/项目成果 19 篇",
    "team_size": "50-100",
    "lab_intro": "由上海创智学院与复旦 NLP 实验室、模思智能联合共建，围绕大语言模型与智能体开展研究，布局模型架构、评测体系与应用场景。",
    "website": "https://xpqiu.github.io/",
    "score": 25,
    "contact": "",
    "contact_note": "",
    "rank": 55
  },
  {
    "id": 54,
    "university": "北京邮电大学（替补）",
    "lab": "DeepTouch Lab @ BUPT",
    "person": "方斌",
    "citations": null,
    "person_intro": "北京邮电大学人工智能学院「拔尖人才」教授、博导，原清华计算机系教师，研究具身智能、灵巧操作与机器人大模型。",
    "publications": "ICRA 2024 共 1 篇，ICLR、IEEE 汇刊等 20 篇",
    "team_size": "10-50",
    "lab_intro": "研究具身触觉感知系统、机器人操作系统、人机交互与灵巧手操作。",
    "website": "https://deeptouch-lab.github.io/publications/",
    "score": 23,
    "contact": "",
    "contact_note": "",
    "rank": 56
  },
  {
    "id": 55,
    "university": "南京大学（替补）",
    "lab": "RINC",
    "person": "申富饶",
    "citations": null,
    "person_intro": "南京大学计算机科学与技术系教授、博士生导师。",
    "publications": "ICML 1 篇、ICLR 1 篇，其余 15 篇",
    "team_size": "10-50",
    "lab_intro": "",
    "website": "https://cs.nju.edu.cn/rinc/Member.html",
    "score": 17,
    "contact": "",
    "contact_note": "",
    "rank": 57
  },
  {
    "id": 58,
    "university": "复旦大学",
    "lab": "集群机器人系统实验室（MagicLab）",
    "person": "丁文超",
    "citations": null,
    "person_intro": "",
    "publications": "",
    "team_size": "",
    "lab_intro": "",
    "website": "",
    "score": null,
    "contact": "",
    "contact_note": "",
    "rank": 58
  },
  {
    "id": 59,
    "university": "南方科技大学",
    "lab": "机器人与自主系统控制与学习（CLEAR）",
    "person": "张巍",
    "citations": null,
    "person_intro": "",
    "publications": "",
    "team_size": "",
    "lab_intro": "",
    "website": "",
    "score": null,
    "contact": "",
    "contact_note": "",
    "rank": 59
  },
  {
    "id": 60,
    "university": "中山大学",
    "lab": "人机物智能融合实验室（SYSU-HCP Lab）",
    "person": "林倞",
    "citations": null,
    "person_intro": "",
    "publications": "",
    "team_size": "",
    "lab_intro": "",
    "website": "",
    "score": null,
    "contact": "",
    "contact_note": "",
    "rank": 60
  },
  {
    "id": 61,
    "university": "南京大学",
    "lab": "具身智能联合创新实验室",
    "person": "",
    "citations": null,
    "person_intro": "",
    "publications": "",
    "team_size": "",
    "lab_intro": "",
    "website": "",
    "score": null,
    "contact": "",
    "contact_note": "",
    "rank": 61
  }
];
